---
title       : Evolución de la Violencia
subtitle    : Reporte Primer Trimestre 2013
author      : Instituto Mexicano para la Competitividad A.C.
job         : 
logo        : IMCO
biglogo     : IMCOBIG
license     : by-nc-sa
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
github:
  user: EduardoClark
  repo: Calculadora
  
  
---


## Escenarios 2013-2018

<iframe src="http://glimmer.rstudio.com/eduardoclark/homicidios/" height=400 width=1000 ></iframe>

<div class='source2'>
<a rel="tooltip" data-original-title="La calculadora proporciona el numero mensual de averiguaciones previas para Homicidios Dolosos que se tendria dada la reducción porcentual en el numero mensual de homicidios al llegar el final de presente sexenio. Adicionalmente se calcula el numero total de APs en el sexenio y la diferencia con respecto al sexenio 2006-2012. Esta calculadora asume una caida lineal constante ">Descripción</a>
</div>

<div class='source3'>
Si no puedes ver la calculadora, refresca tu explorador
</div>

---

## Si México fuera...

<div class='source3'>
Mueve tu cursor sobre el país deseado para visualizar los resultados
</div>



<!-- GeoChart generated in R 2.15.3 by googleVis 0.4.2 package -->
<!-- Fri Apr 19 11:45:48 2013 -->


<!-- jsHeader -->
<script type="text/javascript">
 
// jsData
function gvisDataGeoChartID1a2b753b8e00 () {
  var data = new google.visualization.DataTable();
  var datajson =
[
 [
 " Honduras",
85412,
"Hubiéramos tenido 105,966 homicidios en 2012, 85,412 más que los registrados." 
],
[
 " El Salvador",
59499,
"Hubiéramos tenido  80,053 homicidios en 2012, 59,499 más que los registrados." 
],
[
 "Costa de Marfil",
45270,
"Hubiéramos tenido  65,824 homicidios en 2012, 45,270 más que los registrados." 
],
[
 "Jamaica",
39832,
"Hubiéramos tenido  60,386 homicidios en 2012, 39,832 más que los registrados." 
],
[
 "Venezuela",
31619,
"Hubiéramos tenido  52,173 homicidios en 2012, 31,619 más que los registrados." 
],
[
 "Belize",
27339,
"Hubiéramos tenido  47,893 homicidios en 2012, 27,339 más que los registrados." 
],
[
 "U.S. Virgin Islands",
24794,
"Hubiéramos tenido  45,348 homicidios en 2012, 24,794 más que los registrados." 
],
[
 "Guatemala",
23984,
"Hubiéramos tenido  44,538 homicidios en 2012, 23,984 más que los registrados." 
],
[
 "Saint Kitts and Nevis",
23637,
"Hubiéramos tenido  44,191 homicidios en 2012, 23,637 más que los registrados." 
],
[
 "Zambia",
23405,
"Hubiéramos tenido  43,959 homicidios en 2012, 23,405 más que los registrados." 
],
[
 "Uganda",
21439,
"Hubiéramos tenido  41,993 homicidios en 2012, 21,439 más que los registrados." 
],
[
 " Malawi",
21092,
"Hubiéramos tenido  41,646 homicidios en 2012, 21,092 más que los registrados." 
],
[
 " Lesotho",
20166,
"Hubiéramos tenido  40,720 homicidios en 2012, 20,166 más que los registrados." 
],
[
 " Trinidad y Tobago",
20166,
"Hubiéramos tenido  40,720 homicidios en 2012, 20,166 más que los registrados." 
],
[
 "Sudáfrica",
16233,
"Hubiéramos tenido  36,787 homicidios en 2012, 16,233 más que los registrados." 
],
[
 " Colombia",
15770,
"Hubiéramos tenido  36,324 homicidios en 2012, 15,770 más que los registrados." 
],
[
 " Congo",
15076,
"Hubiéramos tenido  35,630 homicidios en 2012, 15,076 más que los registrados." 
],
[
 "República Centroafricana",
13341,
"Hubiéramos tenido  33,895 homicidios en 2012, 13,341 más que los registrados." 
],
[
 " Bahamas",
11143,
"Hubiéramos tenido  31,697 homicidios en 2012, 11,143 más que los registrados." 
],
[
 " Puerto Rico",
9755,
"Hubiéramos tenido  30,309 homicidios en 2012,  9,755 más que los registrados." 
],
[
 " Santa Lucía",
8598,
"Hubiéramos tenido  29,152 homicidios en 2012,  8,598 más que los registrados." 
],
[
 "República Dominicana",
8367,
"Hubiéramos tenido  28,921 homicidios en 2012,  8,367 más que los registrados." 
],
[
 " Tanzania",
7788,
"Hubiéramos tenido  28,342 homicidios en 2012,  7,788 más que los registrados." 
],
[
 " Sudan",
7441,
"Hubiéramos tenido  27,995 homicidios en 2012,  7,441 más que los registrados." 
],
[
 " Saint Vincent and the Grenadines",
5937,
"Hubiéramos tenido  26,491 homicidios en 2012,  5,937 más que los registrados." 
],
[
 "Etiopía",
5475,
"Hubiéramos tenido  26,029 homicidios en 2012,  5,475 más que los registrados." 
],
[
 " Guinea",
5475,
"Hubiéramos tenido  26,029 homicidios en 2012,  5,475 más que los registrados." 
],
[
 " Dominica",
5012,
"Hubiéramos tenido  25,566 homicidios en 2012,  5,012 más que los registrados." 
],
[
 " Burundi",
4549,
"Hubiéramos tenido  25,103 homicidios en 2012,  4,549 más que los registrados." 
],
[
 "República Democrática del Congo",
4549,
"Hubiéramos tenido  25,103 homicidios en 2012,  4,549 más que los registrados." 
],
[
 " Panama",
4433,
"Hubiéramos tenido  24,987 homicidios en 2012,  4,433 más que los registrados." 
],
[
 " Brasil",
3739,
"Hubiéramos tenido  24,293 homicidios en 2012,  3,739 más que los registrados." 
],
[
 " Equatorial Guinea",
3392,
"Hubiéramos tenido  23,946 homicidios en 2012,  3,392 más que los registrados." 
],
[
 " Guinea-Bissau",
2814,
"Hubiéramos tenido  23,368 homicidios en 2012,  2,814 más que los registrados." 
],
[
 " Kenia",
2698,
"Hubiéramos tenido  23,252 homicidios en 2012,  2,698 más que los registrados." 
],
[
 " Kyrgyzstan",
2698,
"Hubiéramos tenido  23,252 homicidios en 2012,  2,698 más que los registrados." 
],
[
 " Cameroon",
2236,
"Hubiéramos tenido  22,790 homicidios en 2012,  2,236 más que los registrados." 
],
[
 " Montserrat",
2236,
"Hubiéramos tenido  22,790 homicidios en 2012,  2,236 más que los registrados." 
],
[
 "Groenlandia",
1657,
"Hubiéramos tenido  22,211 homicidios en 2012,  1,657 más que los registrados." 
],
[
 " Angola",
1426,
"Hubiéramos tenido  21,980 homicidios en 2012,  1,426 más que los registrados." 
],
[
 " Guyana",
963,
"Hubiéramos tenido  21,517 homicidios en 2012,    963 más que los registrados." 
],
[
 " Ecuador",
500,
"Hubiéramos tenido  21,054 homicidios en 2012,    500 más que los registrados." 
],
[
 " Burkina Faso",
269,
"Hubiéramos tenido  20,823 homicidios en 2012,    269 más que los registrados." 
],
[
 " Eritrea",
38,
"Hubiéramos tenido  20,592 homicidios en 2012,     38 más que los registrados." 
],
[
 " Namibia",
-657,
"Hubiéramos tenido  19,897 homicidios en 2012,    657 menos que los registrados." 
],
[
 " Rwanda",
-772,
"Hubiéramos tenido  19,782 homicidios en 2012,    772 menos que los registrados." 
],
[
 " Chad",
-2276,
"Hubiéramos tenido  18,278 homicidios en 2012,  2,276 menos que los registrados." 
],
[
 " Ghana",
-2392,
"Hubiéramos tenido  18,162 homicidios en 2012,  2,392 menos que los registrados." 
],
[
 "Corea del Norte",
-2970,
"Hubiéramos tenido  17,584 homicidios en 2012,  2,970 menos que los registrados." 
],
[
 " Benin",
-3086,
"Hubiéramos tenido  17,468 homicidios en 2012,  3,086 menos que los registrados." 
],
[
 " Sierra Leone",
-3317,
"Hubiéramos tenido  17,237 homicidios en 2012,  3,317 menos que los registrados." 
],
[
 " Mauritania",
-3549,
"Hubiéramos tenido  17,005 homicidios en 2012,  3,549 menos que los registrados." 
],
[
 " Botswana",
-3780,
"Hubiéramos tenido  16,774 homicidios en 2012,  3,780 menos que los registrados." 
],
[
 " Zimbabwe",
-4011,
"Hubiéramos tenido  16,543 homicidios en 2012,  4,011 menos que los registrados." 
],
[
 " Gabón",
-4590,
"Hubiéramos tenido  15,964 homicidios en 2012,  4,590 menos que los registrados." 
],
[
 " Nicaragua",
-4821,
"Hubiéramos tenido  15,733 homicidios en 2012,  4,821 menos que los registrados." 
],
[
 " French Guiana",
-5168,
"Hubiéramos tenido  15,386 homicidios en 2012,  5,168 menos que los registrados." 
],
[
 "Papúa Nueva Guinea",
-5515,
"Hubiéramos tenido  15,039 homicidios en 2012,  5,515 menos que los registrados." 
],
[
 " Swaziland",
-5631,
"Hubiéramos tenido  14,923 homicidios en 2012,  5,631 menos que los registrados." 
],
[
 " Bermuda",
-6325,
"Hubiéramos tenido  14,229 homicidios en 2012,  6,325 menos que los registrados." 
],
[
 " Comoros",
-6441,
"Hubiéramos tenido  14,113 homicidios en 2012,  6,441 menos que los registrados." 
],
[
 " Nigeria",
-6441,
"Hubiéramos tenido  14,113 homicidios en 2012,  6,441 menos que los registrados." 
],
[
 " Cape Verde",
-7135,
"Hubiéramos tenido  13,419 homicidios en 2012,  7,135 menos que los registrados." 
],
[
 " Grenada",
-7250,
"Hubiéramos tenido  13,304 homicidios en 2012,  7,250 menos que los registrados." 
],
[
 " Paraguay",
-7250,
"Hubiéramos tenido  13,304 homicidios en 2012,  7,250 menos que los registrados." 
],
[
 " Barbados",
-7482,
"Hubiéramos tenido  13,072 homicidios en 2012,  7,482 menos que los registrados." 
],
[
 " Togo",
-7945,
"Hubiéramos tenido  12,609 homicidios en 2012,  7,945 menos que los registrados." 
],
[
 " Gambia",
-8060,
"Hubiéramos tenido  12,494 homicidios en 2012,  8,060 menos que los registrados." 
],
[
 " Perú",
-8639,
"Hubiéramos tenido  11,915 homicidios en 2012,  8,639 menos que los registrados." 
],
[
 " Myanmar",
-8754,
"Hubiéramos tenido  11,800 homicidios en 2012,  8,754 menos que los registrados." 
],
[
 " Rusia",
-8754,
"Hubiéramos tenido  11,800 homicidios en 2012,  8,754 menos que los registrados." 
],
[
 " Liberia",
-8870,
"Hubiéramos tenido  11,684 homicidios en 2012,  8,870 menos que los registrados." 
],
[
 " Costa Rica",
-8986,
"Hubiéramos tenido  11,568 homicidios en 2012,  8,986 menos que los registrados." 
],
[
 " Nauru",
-9217,
"Hubiéramos tenido  11,337 homicidios en 2012,  9,217 menos que los registrados." 
],
[
 " Bolivia",
-10258,
"Hubiéramos tenido  10,296 homicidios en 2012, 10,258 menos que los registrados." 
],
[
 " Mozambique",
-10374,
"Hubiéramos tenido  10,180 homicidios en 2012, 10,374 menos que los registrados." 
],
[
 " Kazakhstan",
-10374,
"Hubiéramos tenido  10,180 homicidios en 2012, 10,374 menos que los registrados." 
],
[
 " Senegal",
-10490,
"Hubiéramos tenido  10,064 homicidios en 2012, 10,490 menos que los registrados." 
],
[
 " Turks and Caicos Islands",
-10490,
"Hubiéramos tenido  10,064 homicidios en 2012, 10,490 menos que los registrados." 
],
[
 " Mongolia",
-10490,
"Hubiéramos tenido  10,064 homicidios en 2012, 10,490 menos que los registrados." 
],
[
 " British Virgin Islands",
-10605,
"Hubiéramos tenido   9,949 homicidios en 2012, 10,605 menos que los registrados." 
],
[
 " Cayman Islands",
-10837,
"Hubiéramos tenido   9,717 homicidios en 2012, 10,837 menos que los registrados." 
],
[
 " Seychelles",
-10952,
"Hubiéramos tenido   9,602 homicidios en 2012, 10,952 menos que los registrados." 
],
[
 " Madagascar",
-11184,
"Hubiéramos tenido   9,370 homicidios en 2012, 11,184 menos que los registrados." 
],
[
 " Indonesia",
-11184,
"Hubiéramos tenido   9,370 homicidios en 2012, 11,184 menos que los registrados." 
],
[
 " Mali",
-11299,
"Hubiéramos tenido   9,255 homicidios en 2012, 11,299 menos que los registrados." 
],
[
 " Pakistan",
-11531,
"Hubiéramos tenido   9,023 homicidios en 2012, 11,531 menos que los registrados." 
],
[
 " Moldova",
-11878,
"Hubiéramos tenido   8,676 homicidios en 2012, 11,878 menos que los registrados." 
],
[
 " Kiribati",
-12109,
"Hubiéramos tenido   8,445 homicidios en 2012, 12,109 menos que los registrados." 
],
[
 " Guadeloupe",
-12456,
"Hubiéramos tenido   8,098 homicidios en 2012, 12,456 menos que los registrados." 
],
[
 " Haiti",
-12572,
"Hubiéramos tenido   7,982 homicidios en 2012, 12,572 menos que los registrados." 
],
[
 " Timor-Leste",
-12572,
"Hubiéramos tenido   7,982 homicidios en 2012, 12,572 menos que los registrados." 
],
[
 " Anguilla",
-12688,
"Hubiéramos tenido   7,866 homicidios en 2012, 12,688 menos que los registrados." 
],
[
 " Antigua and Barbuda",
-12688,
"Hubiéramos tenido   7,866 homicidios en 2012, 12,688 menos que los registrados." 
],
[
 " Lithuania",
-12919,
"Hubiéramos tenido   7,635 homicidios en 2012, 12,919 menos que los registrados." 
],
[
 " Uruguay",
-13729,
"Hubiéramos tenido   6,825 homicidios en 2012, 13,729 menos que los registrados." 
],
[
 " Argentina",
-13844,
"Hubiéramos tenido   6,710 homicidios en 2012, 13,844 menos que los registrados." 
],
[
 " Philippines",
-14307,
"Hubiéramos tenido   6,247 homicidios en 2012, 14,307 menos que los registrados." 
],
[
 "Ucrania",
-14538,
"Hubiéramos tenido   6,016 homicidios en 2012, 14,538 menos que los registrados." 
],
[
 "Estonia",
-14538,
"Hubiéramos tenido   6,016 homicidios en 2012, 14,538 menos que los registrados." 
],
[
 "Cuba",
-14770,
"Hubiéramos tenido   5,784 homicidios en 2012, 14,770 menos que los registrados." 
],
[
 "Bielorrusia",
-14886,
"Hubiéramos tenido   5,668 homicidios en 2012, 14,886 menos que los registrados." 
],
[
 "Estados Unidos",
-15001,
"Hubiéramos tenido   5,553 homicidios en 2012, 15,001 menos que los registrados." 
],
[
 "Tailandia",
-15001,
"Hubiéramos tenido   5,553 homicidios en 2012, 15,001 menos que los registrados." 
],
[
 " Suriname",
-15233,
"Hubiéramos tenido   5,321 homicidios en 2012, 15,233 menos que los registrados." 
],
[
 " Laos",
-15233,
"Hubiéramos tenido   5,321 homicidios en 2012, 15,233 menos que los registrados." 
],
[
 " Georgia",
-15580,
"Hubiéramos tenido   4,974 homicidios en 2012, 15,580 menos que los registrados." 
],
[
 " Martinique",
-15695,
"Hubiéramos tenido   4,859 homicidios en 2012, 15,695 menos que los registrados." 
],
[
 " Turkmenistan",
-15695,
"Hubiéramos tenido   4,859 homicidios en 2012, 15,695 menos que los registrados." 
],
[
 " Yemen",
-15695,
"Hubiéramos tenido   4,859 homicidios en 2012, 15,695 menos que los registrados." 
],
[
 " Palestina",
-15811,
"Hubiéramos tenido   4,743 homicidios en 2012, 15,811 menos que los registrados." 
],
[
 " Albania",
-15927,
"Hubiéramos tenido   4,627 homicidios en 2012, 15,927 menos que los registrados." 
],
[
 " Niger",
-16158,
"Hubiéramos tenido   4,396 homicidios en 2012, 16,158 menos que los registrados." 
],
[
 " Solomon Islands",
-16274,
"Hubiéramos tenido   4,280 homicidios en 2012, 16,274 menos que los registrados." 
],
[
 " Sri Lanka",
-16389,
"Hubiéramos tenido   4,165 homicidios en 2012, 16,389 menos que los registrados." 
],
[
 " India",
-16505,
"Hubiéramos tenido   4,049 homicidios en 2012, 16,505 menos que los registrados." 
],
[
 " Montenegro",
-16505,
"Hubiéramos tenido   4,049 homicidios en 2012, 16,505 menos que los registrados." 
],
[
 " Djibouti",
-16621,
"Hubiéramos tenido   3,933 homicidios en 2012, 16,621 menos que los registrados." 
],
[
 " Cambodia",
-16621,
"Hubiéramos tenido   3,933 homicidios en 2012, 16,621 menos que los registrados." 
],
[
 "Turquía",
-16736,
"Hubiéramos tenido   3,818 homicidios en 2012, 16,736 menos que los registrados." 
],
[
 " Chile",
-16852,
"Hubiéramos tenido   3,702 homicidios en 2012, 16,852 menos que los registrados." 
],
[
 " Taiwan",
-16852,
"Hubiéramos tenido   3,702 homicidios en 2012, 16,852 menos que los registrados." 
],
[
 " Uzbekistan",
-16968,
"Hubiéramos tenido   3,586 homicidios en 2012, 16,968 menos que los registrados." 
],
[
 "Letonia",
-16968,
"Hubiéramos tenido   3,586 homicidios en 2012, 16,968 menos que los registrados." 
],
[
 " Iran",
-17084,
"Hubiéramos tenido   3,470 homicidios en 2012, 17,084 menos que los registrados." 
],
[
 " Libia",
-17199,
"Hubiéramos tenido   3,355 homicidios en 2012, 17,199 menos que los registrados." 
],
[
 " Nepal",
-17315,
"Hubiéramos tenido   3,239 homicidios en 2012, 17,315 menos que los registrados." 
],
[
 " Liechtenstein",
-17315,
"Hubiéramos tenido   3,239 homicidios en 2012, 17,315 menos que los registrados." 
],
[
 " Fiji",
-17315,
"Hubiéramos tenido   3,239 homicidios en 2012, 17,315 menos que los registrados." 
],
[
 " Bangladesh",
-17431,
"Hubiéramos tenido   3,123 homicidios en 2012, 17,431 menos que los registrados." 
],
[
 "Corea del Sur",
-17546,
"Hubiéramos tenido   3,008 homicidios en 2012, 17,546 menos que los registrados." 
],
[
 " Mauritius",
-17662,
"Hubiéramos tenido   2,892 homicidios en 2012, 17,662 menos que los registrados." 
],
[
 " Luxembourg",
-17662,
"Hubiéramos tenido   2,892 homicidios en 2012, 17,662 menos que los registrados." 
],
[
 " Afghanistan",
-17778,
"Hubiéramos tenido   2,776 homicidios en 2012, 17,778 menos que los registrados." 
],
[
 " Malaysia",
-17893,
"Hubiéramos tenido   2,661 homicidios en 2012, 17,893 menos que los registrados." 
],
[
 " Syria",
-17893,
"Hubiéramos tenido   2,661 homicidios en 2012, 17,893 menos que los registrados." 
],
[
 " Azerbaijan",
-18009,
"Hubiéramos tenido   2,545 homicidios en 2012, 18,009 menos que los registrados." 
],
[
 " Kuwait",
-18009,
"Hubiéramos tenido   2,545 homicidios en 2012, 18,009 menos que los registrados." 
],
[
 " Libano",
-18009,
"Hubiéramos tenido   2,545 homicidios en 2012, 18,009 menos que los registrados." 
],
[
 " Finlandia",
-18009,
"Hubiéramos tenido   2,545 homicidios en 2012, 18,009 menos que los registrados." 
],
[
 " Tajikistan",
-18125,
"Hubiéramos tenido   2,429 homicidios en 2012, 18,125 menos que los registrados." 
],
[
 " Israel",
-18125,
"Hubiéramos tenido   2,429 homicidios en 2012, 18,125 menos que los registrados." 
],
[
 " Iraq",
-18240,
"Hubiéramos tenido   2,314 homicidios en 2012, 18,240 menos que los registrados." 
],
[
 " Bulgaria",
-18240,
"Hubiéramos tenido   2,314 homicidios en 2012, 18,240 menos que los registrados." 
],
[
 " Rumania",
-18240,
"Hubiéramos tenido   2,314 homicidios en 2012, 18,240 menos que los registrados." 
],
[
 " São Tomé and Príncipe",
-18356,
"Hubiéramos tenido   2,198 homicidios en 2012, 18,356 menos que los registrados." 
],
[
 " Macedonia",
-18356,
"Hubiéramos tenido   2,198 homicidios en 2012, 18,356 menos que los registrados." 
],
[
 "Jordania",
-18472,
"Hubiéramos tenido   2,082 homicidios en 2012, 18,472 menos que los registrados." 
],
[
 "Chipre",
-18587,
"Hubiéramos tenido   1,967 homicidios en 2012, 18,587 menos que los registrados." 
],
[
 "República Checa",
-18587,
"Hubiéramos tenido   1,967 homicidios en 2012, 18,587 menos que los registrados." 
],
[
 " Bélgica",
-18587,
"Hubiéramos tenido   1,967 homicidios en 2012, 18,587 menos que los registrados." 
],
[
 " Canada",
-18703,
"Hubiéramos tenido   1,851 homicidios en 2012, 18,703 menos que los registrados." 
],
[
 " Vietnam",
-18703,
"Hubiéramos tenido   1,851 homicidios en 2012, 18,703 menos que los registrados." 
],
[
 " Maldives",
-18703,
"Hubiéramos tenido   1,851 homicidios en 2012, 18,703 menos que los registrados." 
],
[
 " Somalia",
-18819,
"Hubiéramos tenido   1,735 homicidios en 2012, 18,819 menos que los registrados." 
],
[
 " Algeria",
-18819,
"Hubiéramos tenido   1,735 homicidios en 2012, 18,819 menos que los registrados." 
],
[
 "Eslovaquia",
-18819,
"Hubiéramos tenido   1,735 homicidios en 2012, 18,819 menos que los registrados." 
],
[
 " Bosnia and Herzegovina",
-18819,
"Hubiéramos tenido   1,735 homicidios en 2012, 18,819 menos que los registrados." 
],
[
 "Grecia",
-18819,
"Hubiéramos tenido   1,735 homicidios en 2012, 18,819 menos que los registrados." 
],
[
 "Marruecos",
-18934,
"Hubiéramos tenido   1,620 homicidios en 2012, 18,934 menos que los registrados." 
],
[
 " Armenia",
-18934,
"Hubiéramos tenido   1,620 homicidios en 2012, 18,934 menos que los registrados." 
],
[
 "Croacia",
-18934,
"Hubiéramos tenido   1,620 homicidios en 2012, 18,934 menos que los registrados." 
],
[
 "Hungría",
-19050,
"Hubiéramos tenido   1,504 homicidios en 2012, 19,050 menos que los registrados." 
],
[
 " Andorra",
-19050,
"Hubiéramos tenido   1,504 homicidios en 2012, 19,050 menos que los registrados." 
],
[
 "Egipto",
-19166,
"Hubiéramos tenido   1,388 homicidios en 2012, 19,166 menos que los registrados." 
],
[
 "Irlanda",
-19166,
"Hubiéramos tenido   1,388 homicidios en 2012, 19,166 menos que los registrados." 
],
[
 "Reino Unido",
-19166,
"Hubiéramos tenido   1,388 homicidios en 2012, 19,166 menos que los registrados." 
],
[
 "Portugal",
-19166,
"Hubiéramos tenido   1,388 homicidios en 2012, 19,166 menos que los registrados." 
],
[
 " Serbia",
-19166,
"Hubiéramos tenido   1,388 homicidios en 2012, 19,166 menos que los registrados." 
],
[
 "Túnez",
-19281,
"Hubiéramos tenido   1,273 homicidios en 2012, 19,281 menos que los registrados." 
],
[
 "Polonia",
-19281,
"Hubiéramos tenido   1,273 homicidios en 2012, 19,281 menos que los registrados." 
],
[
 "Fracia",
-19281,
"Hubiéramos tenido   1,273 homicidios en 2012, 19,281 menos que los registrados." 
],
[
 "Países Bajos",
-19281,
"Hubiéramos tenido   1,273 homicidios en 2012, 19,281 menos que los registrados." 
],
[
 " Samoa",
-19281,
"Hubiéramos tenido   1,273 homicidios en 2012, 19,281 menos que los registrados." 
],
[
 " China",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 " Bhutan",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 "Arabia Saudita",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 "Suecia",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 " Malta",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 " Australia",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 " Tonga",
-19397,
"Hubiéramos tenido   1,157 homicidios en 2012, 19,397 menos que los registrados." 
],
[
 " Qatar",
-19513,
"Hubiéramos tenido   1,041 homicidios en 2012, 19,513 menos que los registrados." 
],
[
 "Dinamarca",
-19513,
"Hubiéramos tenido   1,041 homicidios en 2012, 19,513 menos que los registrados." 
],
[
 "Italia",
-19513,
"Hubiéramos tenido   1,041 homicidios en 2012, 19,513 menos que los registrados." 
],
[
 "Nueva Zelanda",
-19513,
"Hubiéramos tenido   1,041 homicidios en 2012, 19,513 menos que los registrados." 
],
[
 " Vanuatu",
-19513,
"Hubiéramos tenido   1,041 homicidios en 2012, 19,513 menos que los registrados." 
],
[
 " Federated States of Micronesia",
-19513,
"Hubiéramos tenido   1,041 homicidios en 2012, 19,513 menos que los registrados." 
],
[
 "Emiratos Árabes Unidos",
-19629,
"Hubiéramos tenido     925 homicidios en 2012, 19,629 menos que los registrados." 
],
[
 "España",
-19629,
"Hubiéramos tenido     925 homicidios en 2012, 19,629 menos que los registrados." 
],
[
 "Alemania",
-19629,
"Hubiéramos tenido     925 homicidios en 2012, 19,629 menos que los registrados." 
],
[
 " Macau",
-19744,
"Hubiéramos tenido     810 homicidios en 2012, 19,744 menos que los registrados." 
],
[
 " Oman",
-19744,
"Hubiéramos tenido     810 homicidios en 2012, 19,744 menos que los registrados." 
],
[
 "Eslovenia",
-19744,
"Hubiéramos tenido     810 homicidios en 2012, 19,744 menos que los registrados." 
],
[
 "Suiza",
-19744,
"Hubiéramos tenido     810 homicidios en 2012, 19,744 menos que los registrados." 
],
[
 " Bahrain",
-19860,
"Hubiéramos tenido     694 homicidios en 2012, 19,860 menos que los registrados." 
],
[
 "Noruega",
-19860,
"Hubiéramos tenido     694 homicidios en 2012, 19,860 menos que los registrados." 
],
[
 " Austria",
-19860,
"Hubiéramos tenido     694 homicidios en 2012, 19,860 menos que los registrados." 
],
[
 " Guam",
-19860,
"Hubiéramos tenido     694 homicidios en 2012, 19,860 menos que los registrados." 
],
[
 " Brunei",
-19976,
"Hubiéramos tenido     578 homicidios en 2012, 19,976 menos que los registrados." 
],
[
 " Japón",
-20091,
"Hubiéramos tenido     463 homicidios en 2012, 20,091 menos que los registrados." 
],
[
 " French Polynesia",
-20091,
"Hubiéramos tenido     463 homicidios en 2012, 20,091 menos que los registrados." 
],
[
 " Singapore",
-20207,
"Hubiéramos tenido     347 homicidios en 2012, 20,207 menos que los registrados." 
],
[
 "Islandia",
-20207,
"Hubiéramos tenido     347 homicidios en 2012, 20,207 menos que los registrados." 
],
[
 " Hong Kong",
-20323,
"Hubiéramos tenido     231 homicidios en 2012, 20,323 menos que los registrados." 
],
[
 " Monaco",
-20554,
"Hubiéramos tenido       0 homicidios en 2012, 20,554 menos que los registrados." 
],
[
 " Palau",
-20554,
"Hubiéramos tenido       0 homicidios en 2012, 20,554 menos que los registrados." 
] 
];
data.addColumn('string','country');
data.addColumn('number','Hubieramos tenido');
data.addColumn({
    type: 'string',
    role: 'tooltip'
});
data.addRows(datajson);
return(data);
}
 
// jsDrawChart
function drawChartGeoChartID1a2b753b8e00() {
  var data = gvisDataGeoChartID1a2b753b8e00();
  var options = {};
options["width"] = 1000;
options["height"] = 500;
options["colorAxis"] = {minValue: -20000, maxValue: 20000 , colors: ['royalblue' ,'white', 'red']};
options["legend"] = {numberFormat: "###,###'"};

     var chart = new google.visualization.GeoChart(
       document.getElementById('GeoChartID1a2b753b8e00')
     );
     chart.draw(data,options);
    

}
  
 
// jsDisplayChart
(function() {
  var pkgs = window.__gvisPackages = window.__gvisPackages || [];
  var callbacks = window.__gvisCallbacks = window.__gvisCallbacks || [];
  var chartid = "geochart";

  // Manually see if chartid is in pkgs (not all browsers support Array.indexOf)
  var i, newPackage = true;
  for (i = 0; newPackage && i < pkgs.length; i++) {
    if (pkgs[i] === chartid)
      newPackage = false;
  }
  if (newPackage)
    pkgs.push(chartid);

  // Add the drawChart function to the global list of callbacks
  callbacks.push(drawChartGeoChartID1a2b753b8e00);
})();
function displayChartGeoChartID1a2b753b8e00() {
  var pkgs = window.__gvisPackages = window.__gvisPackages || [];
  var callbacks = window.__gvisCallbacks = window.__gvisCallbacks || [];
  window.clearTimeout(window.__gvisLoad);
  // The timeout is set to 100 because otherwise the container div we are
  // targeting might not be part of the document yet
  window.__gvisLoad = setTimeout(function() {
    var pkgCount = pkgs.length;
    google.load("visualization", "1", { packages:pkgs, callback: function() {
      if (pkgCount != pkgs.length) {
        // Race condition where another setTimeout call snuck in after us; if
        // that call added a package, we must not shift its callback
        return;
      }
      while (callbacks.length > 0)
        callbacks.shift()();
    } });
  }, 100);
}
 
// jsFooter
 </script>
 
<!-- jsChart -->
<script type="text/javascript" src="https://www.google.com/jsapi?callback=displayChartGeoChartID1a2b753b8e00"></script>
 
<!-- divChart -->
  
<div id="GeoChartID1a2b753b8e00"
  style="width: 1000px; height: 1000px;">
</div>

<div class='source4'>
<a rel="tooltip" data-original-title="El gráfico presenta el numero de homicidios que hubieran ocurrido en México en 2012 si se tuviera la tasa de homicidios del país seleccionado. <br> Adicionalmente se incluye la diferencia en el numero de homicidios en 2012 y los que se hubieran tenido bajo la tasa del país seleccionado. <br> (Se utilizó el numero de averiguaciones previas por homicidio doloso del SESNSP)">Descripción</a>
</div>

